function startup
%
%
% function startup
%
% Runs on Matlab startup. Ensures that all my machines have the
% same Matlab environment. 


%Set Matlab defaults   
set(0, 'DefaultFigureColor', 'w')

%Handle custom paths

%2-Photon Imaging Toolbox
twoPtoolbox={'~/work/Matlab_Scripts/CellSort1.3',...
         '~/work/Matlab_Scripts/ImagingAnalysis/',...
         '~/work/Matlab_Scripts/ImagingAnalysis/findNuclei',...
         '~/work/Matlab_Scripts/ImagingAnalysis/import',...
         '~/work/Matlab_Scripts/ImagingAnalysis/preProcessing',...
         '~/work/Matlab_Scripts/ImagingAnalysis/display',...
         '~/work/Matlab_Scripts/ImagingAnalysis/ROIstats',...
         '~/work/Matlab_Scripts/ImagingAnalysis/KCtuningCurves',...
         '~/work/Matlab_Scripts/ImagingAnalysis/utilityFunctions',...
         '~/work/Matlab_Scripts/ImagingAnalysis/summarizeRecording',...
         '~/work/Matlab_Scripts/ImagingAnalysis/DiscriminantAnalysis',...
         '~/work/Matlab_Scripts/ImagingAnalysis/unsupervisedClustering',...
         '~/work/Matlab_Scripts/ImagingAnalysis/testCode',...
         '~/work/Matlab_Scripts/ImagingAnalysis/registrationFunctions',...         
         '~/work/Matlab_Scripts/ImagingAnalysis/registrationFunctions/demon',...         
         '~/work/Matlab_Scripts/ImagingAnalysis/registrationFunctions/demon/functions_nonrigid',...
         '~/work/Matlab_Scripts/ImagingAnalysis/registrationFunctions/elastix',...         
         '~/work/Matlab_Scripts/ImagingAnalysis/registrationFunctions/ffttrans',...         
         '~/work/Matlab_Scripts/ImagingAnalysis/registrationFunctions/gkerr',...         
         '~/work/Matlab_Scripts/ImagingAnalysis/registrationFunctions/symmetric',...        
         '~/work/Matlab_Scripts/CMTK_registration/matlab'};

%TissueCyte-related stuff
tissueCyte={'~/work/TissueCyte/code/MATLAB'};

%TV stitching and basic analysis
tvMat={'~/work/TissueCyte/code/tvMat/artifactCorrection',...
       '~/work/TissueCyte/code/tvMat/INI',...
       '~/work/TissueCyte/code/tvMat/utils',...
       '~/work/TissueCyte/code/tvMat/stitchedStackManipulation',...
       '~/work/TissueCyte/code/tvMat/processDuringAcquistion',...
       '~/work/TissueCyte/code/tvMat/visualisations',...
       '~/work/TissueCyte/code/tvMat/stitching',...
       '~/work/TissueCyte/code/tvMat/testingFunctions',....
       '~/work/TissueCyte/code/tvMat/GradientDomain'};

%Aligning to ARA
araTools={'~/work/Anatomy/code/ARA_tools/atlas_utils/',...
          '~/work/Anatomy/code/ARA_tools/settings/',...
          '~/work/Anatomy/code/ARA_tools/data_points_utils/',...
          '~/work/Anatomy/code/ARA_tools/utils/',...
          '~/work/Anatomy/code/ARA_tools/plotting/summary/',...
          '~/work/Anatomy/code/ARA_tools/plotting/projections/'};

%Elastix Matlab wrapper which also requires the ymlreader
MelastiX={'~/work/Matlab_Scripts/MelastiX'};
yml={'~/work/Matlab_Scripts/yml'};
     
goggleViewer={'~/work/TissueCyte/code/goggleviewer/',...
              '~/work/TissueCyte/code/goggleviewer/classes',...
              '~/work/TissueCyte/code/goggleviewer/classes/infoBoxes',...
              '~/work/TissueCyte/code/goggleviewer/classes/EventDataSubclasses',...
              '~/work/TissueCyte/code/goggleviewer/fileIO',...
              '~/work/TissueCyte/code/goggleviewer/imageProcessingModules',...
              '~/work/TissueCyte/code/goggleviewer/plugins',...
              '~/work/TissueCyte/code/goggleviewer/plugins/goggleMarkers',...
              '~/work/TissueCyte/code/goggleviewer/plugins/tutorials',...
              '~/work/TissueCyte/code/goggleviewer/resources',...
              '~/work/TissueCyte/code/goggleviewer/resources/corePlugins',...
              '~/work/TissueCyte/code/goggleviewer/resources/readQueueSize',...
              '~/work/TissueCyte/code/goggleviewer/resources/yaml',...
              '~/work/TissueCyte/code/goggleviewer/resources/memory'};

TIFFStack ={'~/work/Matlab_Scripts/TIFFStack'};

slacklab={'~/work/Matlab_Scripts/SlackMatlab'};

matlab_tree={'~/work/Matlab_Scripts/matlab-tree'};
             

if isunix && ~ismac
  icy='/opt/icy/plugins/ylemontag/matlabcommunicator';
else
  icy='';
end

fprintf('Adding personal directories to MATLAB path\n')
addpath(...
    matlab_tree{:},...
    araTools{:},...
    MelastiX{:},... %Takes precedence over functions with identical names in the 2-p toolbox
    yml{:},...
    goggleViewer{:},... %put above tvMat so this copy of openTiff takes precendence
    tvMat{:},...
    icy,...
    TIFFStack{:},...
    slacklab{:},...
    twoPtoolbox{:},...
    '~/work/Matlab_Scripts/Jefferis_MatlabSupport/nrrdio',...
    '~/work/Matlab_Scripts/export_fig',...
    '~/work/Matlab_Scripts/m2html',...
    '~/work/Matlab_Scripts/libSVMwrapper',...
    '~/work/Matlab_Scripts/multiprod',...
    '~/work/Matlab_Scripts/ICP_finite',...
    '~/work/Matlab_Scripts/jsonlab',...
    '~/work/Matlab_Scripts/latexRelated',...
    '~/work/Matlab_Scripts/lle',...
    '~/work/Matlab_Scripts/FastICA_25',...
    '~/work/Matlab_Scripts/plotting',...
    '~/work/Matlab_Scripts/plotting/plot2svg',...
    '~/work/Matlab_Scripts/plotting/real2rgb',...
    '~/work/Matlab_Scripts/plotting/distributionPlot',...
    '~/work/Matlab_Scripts/stats',...
    '~/work/Matlab_Scripts/settings',...
    '~/work/Matlab_Scripts/toys',...
    '~/work/Matlab_Scripts/misc',...
    '~/work/Matlab_Scripts/maths');

%Move to the start of the list, allowing settings files kept here to mask others
addpath('~/work/Matlab_Scripts/')


if ~isempty(icy)
    try
        icy_init
    catch
        disp('icy init failed')
    end
    
end
